# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2b62f02e3e002791c7702de36e09d45636693a7e3af8fe8b9120a05ff271339ca18f31a12995a9fd489e165f412943fd5e2d887649764b018126c1c3764182c

test:
  secret_key_base: 0598a2aa3c84e258a615b64822c175aa8b938d7f04ffddf01730a2112d52ee1339c12af779d394d0c456660cca61e1243c48cd89bb9b853d19d1cd4128b6028f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
